# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import demo_pb2 as demo__pb2


class AddServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddFunc = channel.unary_unary(
        '/AddService/AddFunc',
        request_serializer=demo__pb2.AddRequest.SerializeToString,
        response_deserializer=demo__pb2.AddResponse.FromString,
        )


class AddServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddFunc(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AddServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddFunc': grpc.unary_unary_rpc_method_handler(
          servicer.AddFunc,
          request_deserializer=demo__pb2.AddRequest.FromString,
          response_serializer=demo__pb2.AddResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AddService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
